### PR TITLE
Update to spring_2017.yaml (including Crunchyroll, Animelab, Funimation, Amazon + more)

### PR DESCRIPTION
**Pull request by mnmt**
Saw your comment on [this reddit post](https://www.reddit.com/r/anime/comments/65cpe9/spoilers_seikaisuru_kado_episode_2_discussion/), hope this update is helpful. Sorry if my addition of other stream locations has been done in a way that causes problems, I just updated the Crunchyroll links and then just kept making other changes (including fixing the Eccentric Family S2 link). 

(BTW, would there be a way of adding an option into the config that could allow regions to be manually added to the config for shows ? I guess this would also need a nice, by default hidden/minimised way of said information being presented on a reddit post too, but I like the idea of having that information somehow present.)

Commit info below:

Added new links to shows announced more recently for the spring 2017 lineup, e.g. Tsugumomo, Renai Boukun and Sin: Nanatsu no Taizai. Links have also been added for Funimation, Amazon (US & UK listed), Animelab (AU & NZ only), The Anime Network Online, and Netflix (once).

Corrections have been made to the string delimiters for link of "Monster Strike 2", and link for Uchouten Kazoku 2 corrected to the season 2 repository.

Shows with working links with episodes present (such as Tsuki ga Kirei, Sakura Quest, Seikaisuru Kado, Re: Creators) had the `has_source` property changed to `true` ; I am not certain if this change is the correct one.

Funimation links are given for their announced simuldubs (links are empty strings for announced but as-yet not listed simuldubs). Funimation links also auto-direct (thanks Funimation :) ) to the equivalent funimationnow.uk links for UK users. 

Amazon links have been made for the US (which all appear to be under the Anime Strike "channel" in addition to Amazon Prime), and for the UK. Each region has its own link to each show (where available) so a link to some kind of search instead might be preferred. Linking to each region individually would not only be an tedious task, but also a massive clutter to the reddit post. I blame amazon personally :P

Animelab links added for announced series (links are empty strings for announced but as-yet unlisted pages).

The Anime Network Online links added for two shows, and Netflix for ID-0 (though not yet airing).

### CODE REVIEW

**Comment by lilyhilldev** [comment]
The `has_source` property is used for shows that are adapted from existing source material (manga/LN/novel/other) so that the bot displays a message reminding users to not talk about spoilers. Re:Creators, Seikaisuru Kado, Sakura Quest etc are all original series and have `has_source` set to false. I'm pretty confident I got everything correct but please make corrections if needed.

Regarding the streaming links, my understanding is that there is some backend implementation that is necessary for the streaming links to show up in the thread. Enigma's wording in the reddit thread suggests that if there is a streaming link present then the bot will watch for the official release rather than whenever it gets put up on nyaa. I only added Crunchy links because I'm certain the bot supports that but I'm unsure of the other services. @TheEnigmaBlade if you could clarify that'd be great :)

**Comment by mnmt** [comment]
@andrewhillcode 
Thanks for the info on `has_source`, I'll correct for my changes there. 

I understand that right now there is no backend support for other streaming sites apart from Crunchyroll as part of the bot. I was hoping that the the bot, via what I've entered in the config file, would handle and display the links to the legal streaming pages listed regardless of whether it detects the episode on Nyaa or on Crunchyroll.  It would also be useful for when it streams on Crunchyroll in the US but on other sites within other countries, since the detection logic can only needs to handle Crunchyroll but legal stream links, once manually entered, can easily be present. 

I haven't looked at the logic for how the config file is interpreted (I did once try to have a go and understand the bot well enough to make contributions but I think the whole thing is still a bit beyond me :/)

But I can imagine that if a listing for a show has to be added manuall to the config for reddit posts to be generated weekly, and whether a Crunchyroll link is present or not determines whether it watches for that show on Crunchyroll or on Nyaa, then it cannot be too much of a change to adapt it so that any streams entires for a show are ignored as if nothing is present for the purpose of choosing tracking, but displayed on reddit posts for users to use. It may even do this already, but I cannot tell myself.

Sorry I couldn't do more myself, just wanted to help out with getting links to shows together and went a bit overboard after adding Crunchyroll's.

**Comment by TheEnigmaBlade** [comment]
Sorry for seeing this *really* late, but I never got an email notification from github about it. -_-

I appreciate your effort, but there's a lot wrong with these changes that would cause the config import to fail. I can't fix them at the moment, so you might be able to get to them before I can.

* The values under the `streams:` object are *not* using the format `name: url`: they're using the format `key: url`, where `key` is the internal key used by the bot for each known service listed [here](https://github.com/TheEnigmaBlade/holo/tree/master/src/services/stream). Keys like `AnimeLab (AU & NZ)` and `amazon (US, Prime & Anime Strike)` don't exist.

* Along the same lines as above, you can't add Crunchyroll's regions in parentheses in the key because they become part of the key. `crunchyroll` is valid, but `crunchyroll (UK,IE,SE,NO,DK,IS,FI)` is not valid.

* A service is only supported if it's known by the bot (it's registered as a service [here](https://github.com/TheEnigmaBlade/holo/tree/master/src/services/stream)), because the bot needs to know how to digest and re-form show URLs (the entire URL isn't stored). Services like Netflix, AnimeLab, and Anime Network Online are currently not supported. It's not that difficult to add support—[Amazon](https://github.com/TheEnigmaBlade/holo/blob/master/src/services/stream/amazon.py) is a good example of a minimal implementation—but they nevertheless must be supported before they can be listed in the season config.

**Comment by mnmt** [comment]
Sorry for the trouble @TheEnigmaBlade , I had a feeling that what I'd done might not work out so I'm sorry for making a pull request with so many errors :3 .

When I next get a chance I'll make a separate pull request which has just the CR links with just "crunchyroll" as the key for each show, so that it can be pulled in without issue and the bot can start reporting those streams for the time being.

Since the format is `key:url`, I can see that my idea is kinda stupid. However I do think the ability to add to the config `name:url` pairs that get posted as part of the reddit post could be really handy for sites that are not supported or tracked, though I guess I should put this suggestion/feature as a Github issue instead of here :P. With Nyaa going down for good though, I guess it is even more important that the bot has a working tracker for at least one of the sites it appears on.

(Also, I really hate the way amazon does it's links for streams, a different one for each tld, with each uploaded to at different times is really silly.)

**Comment by mnmt** [comment]
So I'm happy for this malformed pull request to be closed, but so I can try to make an improved pull request at some point in the future, please could take a look at the following queries 🙏:

Having taken a look at the [`funimation.py` ](https://github.com/TheEnigmaBlade/holo/blob/master/src/services/stream/funimation.py) and [`funimation_new.py`](https://github.com/TheEnigmaBlade/holo/blob/master/src/services/stream/funimation_new.py) service classes, I'm not super clear whether I should have the `key` in the config for funimation shows be `funimation` or `funimation_new`. 

I'm also not really sure how to handle doing Amazon shows, since the unique show identifier is different for each domain Amazon show that show in (e.g. Re: Creators :  {'US :us: ':'B06Y3WYQHG', 'UK :gb: ':'B06Y5HSYLT', 'DE :de: ':'B071Y123Y1',...}), with each unique key only working for the correct country TLD. So the class can currently handle US :us: show urls correctly, but no others. Even if the bot is just limited providing links streaming for English speaking regions (and I can't find much on .com.au or .ca for recent amazon anime), it would probably not be a good approach to just make a handler for each country that amazon is streaming anime for ? Though maybe one for just the UK :gb: would be good :D

I guess the animenetwork urls as written in previous commits should work pretty well, so I could add those easily enough. Though [it seems ](https://github.com/TheEnigmaBlade/holo/blob/master/src/services/stream/animenetwork.py#L14) to pass ("amazon","Amazon",False) to the [`AbstractServiceHandler`](https://github.com/TheEnigmaBlade/holo/blob/master/src/services/__init__.py#L138) (if I understand super correctly), which I imagine is a bug ?

With the example of the Amazon handler, me making one for Animelab shouldn't be too hard, and I'll have a go at it at some point. I won't bother with Netflix though, if they won't release things weekly.

Finally, is `crunchyroll: ''` required alongside for each show that hasn't got an actual CR url, I'm curious since I found `crunchyroll: ''` to be listed by default under each and every non-CR stream option ?

Thank you for you help and time @TheEnigmaBlade :)

**Pull request closed without merging**
